// Code generated by querygen.
// You may only edit import statements.
package simple

import (
	"github.com/sourcegraph/querygen/lib/interpolate"
)

type selectAllQueryParams struct {
	tableName string
}

var _ interpolate.QueryParams = &selectAllQueryParams{}

func (qp *selectAllQueryParams) FormatSpecifiers() []string {
	return []string{"%s"}
}

func (qp *selectAllQueryParams) FormatArgs() []any {
	return []any{qp.tableName}
}
