// Code generated by querygen.
// You may only edit import statements.
package simple

import (
	"github.com/sourcegraph/querygen/lib/interpolate"
)

type selectAllQueryVars struct {
	tableName string
}

var _ interpolate.QueryVars = &selectAllQueryVars{}

func (qp *selectAllQueryVars) FormatSpecifiers() []string {
	return []string{"%s"}
}

func (qp *selectAllQueryVars) FormatArgs() []any {
	return []any{qp.tableName}
}
