// Code generated by querygen.
// You may only edit import statements.
package simple

import (
	"github.com/sourcegraph/querygen/lib/interpolate"
	_ "math" // Added by hand
)

type myQueryParams struct {
	abc string
}

var _ interpolate.QueryParams = &myQueryParams{}

func (qp *myQueryParams) FormatSpecifiers() []string {
	return []string{"%s"}
}

func (qp *myQueryParams) FormatArgs() []any {
	return []any{qp.abc}
}
