// Code generated by querygen.
// You may only edit import statements.
package interpolate

type myArgsQueryParams struct {
	TableName string
	WantId    int
}

var _ QueryParams = &myArgsQueryParams{}

func (qp *myArgsQueryParams) FormatSpecifiers() []string {
	return []string{"%s", "%d"}
}

func (qp *myArgsQueryParams) FormatArgs() []any {
	return []any{qp.TableName, qp.WantId}
}

type partyAttendeesQueryParams struct {
	partyId int
}

var _ QueryParams = &partyAttendeesQueryParams{}

func (qp *partyAttendeesQueryParams) FormatSpecifiers() []string {
	return []string{"%d"}
}

func (qp *partyAttendeesQueryParams) FormatArgs() []any {
	return []any{qp.partyId}
}

type bestChoiceCakeQueryParams struct {
	partyId          int
	excludedCakeType string
}

var _ QueryParams = &bestChoiceCakeQueryParams{}

func (qp *bestChoiceCakeQueryParams) FormatSpecifiers() []string {
	return []string{"%d", "%s"}
}

func (qp *bestChoiceCakeQueryParams) FormatArgs() []any {
	return []any{qp.partyId, qp.excludedCakeType}
}
